name: Deploy to IPFS
on:
  push:
    branches:
      - main
jobs:
  deploy-to-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - run: npm run build
      - uses: web3-storage/add-to-web3@v2
        id: w3s
        with:
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN }}
          path_to_add: 'build'
      - uses: nvrabii/ipns-update-revision@v1
        with:
          signing_key: ${{ secrets.IPNS_SIGNING_KEY }}
          new_cid: ${{ steps.w3s.outputs.cid }}
